spring:
  application:
    name: UnitServiceApplication
  profiles:
    active: dev
info:
  version: ${project.version}
endpoints:
  shutdown:
    enabled: true
server:
  port: 8080
mongeez:
  location: mongo-changelog/changelog-master.xml
---

security:
  oauth2:
    resource:
      resourceId: burraq
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
          rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
          fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
          LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
          kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
          jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
          JwIDAQAB
          -----END PUBLIC KEY-----

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: unit-service

---
spring:
  profiles: docker
  data:
    mongodb:
      host: unitservicedb
      database: unit-service