spring:
  application:
    name: unit-service
  profiles:
    active: dev
info:
  version: '@project.version@'
endpoints:
  shutdown:
    enabled: true
server:
  port: 8080
mongeez:
  location: mongo-changelog/changelog-master.xml
eureka:
  client:
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: unit-service

---
spring:
  profiles: docker
  data:
    mongodb:
      host: unitservicedb
      database: unit-service
